import type { AppData } from './types'

export function seedData(): AppData {
  return {
    artist: {
      stageName: 'NOVA',
      realName: 'Léa Moreau',
      genre: 'Électro-pop',
      city: 'Paris, FR',
      photo: '',
      bio: "Artiste électro-pop basée à Paris. Premier album « Aurora » prévu pour août 2026.",
      email: 'contact@nova-music.fr',
      phone: '+33 6 00 00 00 00',
      instagram: '@nova.music',
      spotify: 'NOVA',
      website: 'nova-music.fr',
    },
    label: {
      name: 'Halo Records',
      tagline: 'Label indépendant · Électro-pop & nouvelles scènes',
      founded: '2019',
      location: 'Paris, France',
      email: 'contact@halorecords.fr',
      website: 'halorecords.fr',
      distribution: 'Believe Distribution',
      publishing: 'Sony Music Publishing',
      roster: [
        { name: 'NOVA', genre: 'Électro-pop' },
        { name: 'Kaïto', genre: 'Hyperpop' },
        { name: 'Lune Bleue', genre: 'Indie' },
        { name: 'Mira V.', genre: 'R&B alternatif' },
      ],
    },
    contracts: [
      {
        id: 'c1',
        title: "Contrat d'enregistrement — Album « Aurora »",
        party: 'Halo Records',
        type: 'Enregistrement',
        status: 'Actif',
        startDate: '2025-02-01',
        endDate: '2028-02-01',
        value: 45000,
        royaltyRate: 22,
        notes: '3 albums, avance récupérable. Option label pour 2 albums supplémentaires.',
      },
      {
        id: 'c2',
        title: "Contrat d'édition musicale",
        party: 'Sony Music Publishing',
        type: 'Édition',
        status: 'Actif',
        startDate: '2025-03-15',
        endDate: '2030-03-15',
        value: 30000,
        royaltyRate: 50,
        notes: 'Édition du catalogue 2025-2030. Partage 50/50 sur droits mécaniques.',
      },
      {
        id: 'c3',
        title: 'Mandat de booking — Tournée 2026',
        party: 'Live Nation France',
        type: 'Booking',
        status: 'En négociation',
        startDate: '2026-09-01',
        endDate: '2027-06-30',
        value: 0,
        royaltyRate: 85,
        notes: 'Commission agence 15%. En attente des dates de salles.',
      },
      {
        id: 'c4',
        title: 'Licence sync — Spot TV « Été Vibrant »',
        party: 'Publicis Conseil',
        type: 'Licence',
        status: 'En attente signature',
        startDate: '2026-08-01',
        endDate: '2027-08-01',
        value: 12000,
        royaltyRate: 100,
        notes: 'Utilisation du titre « Néon » — diffusion France, 12 mois.',
      },
    ],
    concerts: [
      {
        id: 'g1',
        venue: 'La Cigale',
        city: 'Paris',
        country: 'France',
        date: '2026-08-14',
        time: '20:30',
        status: 'Confirmé',
        capacity: 1389,
        ticketsSold: 1120,
        fee: 8500,
        promoter: 'Live Nation',
        notes: 'Release party de l’album. Balances 16h.',
      },
      {
        id: 'g2',
        venue: 'Rockhal',
        city: 'Esch-sur-Alzette',
        country: 'Luxembourg',
        date: '2026-09-05',
        time: '21:00',
        status: 'Confirmé',
        capacity: 1200,
        ticketsSold: 640,
        fee: 6000,
        promoter: 'den Atelier',
        notes: '',
      },
      {
        id: 'g3',
        venue: 'Le Transbordeur',
        city: 'Lyon',
        country: 'France',
        date: '2026-09-19',
        time: '20:00',
        status: 'Option',
        capacity: 1800,
        ticketsSold: 0,
        fee: 7000,
        promoter: 'Totaal Rez',
        notes: 'Option jusqu’au 15/08.',
      },
      {
        id: 'g4',
        venue: 'AB Club',
        city: 'Bruxelles',
        country: 'Belgique',
        date: '2026-10-03',
        time: '20:30',
        status: 'Annoncé',
        capacity: 300,
        ticketsSold: 90,
        fee: 3500,
        promoter: 'Ancienne Belgique',
        notes: '',
      },
      {
        id: 'g5',
        venue: 'Festival Les Nuits Sonores',
        city: 'Lyon',
        country: 'France',
        date: '2026-05-28',
        time: '22:15',
        status: 'Terminé',
        capacity: 5000,
        ticketsSold: 5000,
        fee: 15000,
        promoter: 'Arty Farty',
        notes: 'Set de 60 min. Excellent retour presse.',
      },
    ],
    releases: [
      {
        id: 'r1',
        title: 'Aurora',
        type: 'Album',
        date: '2026-08-14',
        status: 'Master prêt',
        cover: '#8b5cf6',
        streams: 0,
        isrc: 'FR-Z03-26-00001',
        featuring: '',
        notes: '11 titres. Pochette validée. Promo dès le 20/07.',
      },
      {
        id: 'r2',
        title: 'Néon',
        type: 'Single',
        date: '2026-06-06',
        status: 'Publié',
        cover: '#ec4899',
        streams: 1240000,
        isrc: 'FR-Z03-26-00002',
        featuring: '',
        notes: 'Premier extrait de l’album. Playlist « New Music Friday ».',
      },
      {
        id: 'r3',
        title: 'Gravité',
        type: 'Single',
        date: '2026-07-18',
        status: 'Publié',
        cover: '#3b82f6',
        streams: 480000,
        isrc: 'FR-Z03-26-00003',
        featuring: 'Kaïto',
        notes: 'Second extrait, feat. Kaïto.',
      },
      {
        id: 'r4',
        title: 'Horizon (Remix)',
        type: 'Remix',
        date: '2026-09-12',
        status: 'Planifié',
        cover: '#10b981',
        streams: 0,
        isrc: '',
        featuring: '',
        notes: 'Remix club, en attente du master.',
      },
    ],
    royalties: [
      { id: 'y1', platform: 'Spotify', period: 'Juin 2026', streams: 820000, amount: 2870, color: '#1db954' },
      { id: 'y2', platform: 'Apple Music', period: 'Juin 2026', streams: 240000, amount: 1680, color: '#000000' },
      { id: 'y3', platform: 'Deezer', period: 'Juin 2026', streams: 130000, amount: 690, color: '#8b5cf6' },
      { id: 'y4', platform: 'YouTube Music', period: 'Juin 2026', streams: 310000, amount: 540, color: '#ff0000' },
      { id: 'y5', platform: 'Amazon Music', period: 'Juin 2026', streams: 70000, amount: 420, color: '#25d1da' },
      { id: 'y6', platform: 'Spotify', period: 'Mai 2026', streams: 610000, amount: 2130, color: '#1db954' },
      { id: 'y7', platform: 'Apple Music', period: 'Mai 2026', streams: 190000, amount: 1330, color: '#000000' },
      { id: 'y8', platform: 'Deezer', period: 'Mai 2026', streams: 95000, amount: 500, color: '#8b5cf6' },
      { id: 'y9', platform: 'YouTube Music', period: 'Mai 2026', streams: 250000, amount: 430, color: '#ff0000' },
    ],
    studio: [
      {
        id: 's1',
        title: 'Enregistrement voix — « Horizon »',
        studio: 'Studio Ferber',
        date: '2026-08-04',
        startTime: '10:00',
        endTime: '16:00',
        type: 'Enregistrement',
        cost: 650,
        engineer: 'Thomas R.',
        notes: 'Prévoir les topline finales.',
      },
      {
        id: 's2',
        title: 'Session mix — 3 titres',
        studio: 'La Frette Studios',
        date: '2026-08-08',
        startTime: '14:00',
        endTime: '20:00',
        type: 'Mix',
        cost: 900,
        engineer: 'Manon L.',
        notes: '',
      },
      {
        id: 's3',
        title: 'Répétition tournée',
        studio: 'HF Studios',
        date: '2026-08-11',
        startTime: '13:00',
        endTime: '18:00',
        type: 'Répétition',
        cost: 300,
        engineer: '—',
        notes: 'Filage complet du set + technique.',
      },
      {
        id: 's4',
        title: 'Mastering album « Aurora »',
        studio: 'Translab',
        date: '2026-07-31',
        startTime: '11:00',
        endTime: '15:00',
        type: 'Mastering',
        cost: 1200,
        engineer: 'Chab',
        notes: 'Master final avant pressage.',
      },
      {
        id: 's5',
        title: 'Session écriture',
        studio: 'Home Studio',
        date: '2026-08-20',
        startTime: '15:00',
        endTime: '19:00',
        type: 'Écriture',
        cost: 0,
        engineer: '—',
        notes: 'Nouveaux morceaux pour EP 2027.',
      },
    ],
    contacts: [
      {
        id: 'k1',
        name: 'Sophie Delatour',
        role: 'Directrice de label',
        company: 'Halo Records',
        category: 'Label',
        email: 'sophie@halorecords.fr',
        phone: '+33 6 12 34 56 78',
        favorite: true,
        notes: 'Interlocutrice principale. Point hebdo le lundi.',
      },
      {
        id: 'k2',
        name: 'Marc Vasseur',
        role: 'Agent / Booker',
        company: 'Live Nation France',
        category: 'Booking',
        email: 'm.vasseur@livenation.fr',
        phone: '+33 6 98 76 54 32',
        favorite: true,
        notes: 'Gère la tournée 2026.',
      },
      {
        id: 'k3',
        name: 'Julie Nkomo',
        role: 'Attachée de presse',
        company: 'Pressing Agency',
        category: 'Média',
        email: 'julie@pressing.agency',
        phone: '+33 7 11 22 33 44',
        favorite: false,
        notes: 'Promo album « Aurora ».',
      },
      {
        id: 'k4',
        name: 'Thomas Renard',
        role: 'Ingénieur du son',
        company: 'Studio Ferber',
        category: 'Studio',
        email: 'thomas@studioferber.com',
        phone: '+33 6 55 44 33 22',
        favorite: false,
        notes: '',
      },
      {
        id: 'k5',
        name: 'Me Claire Aubert',
        role: 'Avocate spécialisée musique',
        company: 'Aubert & Associés',
        category: 'Juridique',
        email: 'c.aubert@aubert-legal.fr',
        phone: '+33 1 42 00 00 00',
        favorite: false,
        notes: 'Relecture des contrats.',
      },
      {
        id: 'k6',
        name: 'David Klein',
        role: 'Manager',
        company: 'DK Management',
        category: 'Management',
        email: 'david@dkmanagement.com',
        phone: '+33 6 77 88 99 00',
        favorite: true,
        notes: 'Coordination générale de carrière.',
      },
    ],
  }
}
