import type { AppData } from './types'

/** Date ISO située il y a `h` heures — le fil paraît ainsi toujours récent. */
function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 3_600_000).toISOString()
}

export function seedData(): AppData {
  return {
    onboarded: true,
    artist: {
      stageName: 'NOVA',
      realName: 'Léa Moreau',
      genre: 'Électro-pop',
      city: 'Paris, FR',
      photo: '',
      bio: "Artiste électro-pop basée à Paris. Premier album « Aurora » prévu pour août 2026.",
      email: 'contact@nova-music.fr',
      phone: '+33 6 00 00 00 00',
      instagram: '@nova.music',
      spotify: 'NOVA',
      website: 'nova-music.fr',
    },
    subscription: { plan: 'free', since: '' },
    label: {
      name: 'Halo Records',
      tagline: 'Label indépendant · Électro-pop & nouvelles scènes',
      founded: '2019',
      location: 'Paris, France',
      email: 'contact@halorecords.fr',
      website: 'halorecords.fr',
      distribution: 'Believe Distribution',
      publishing: 'Sony Music Publishing',
      roster: [
        { name: 'NOVA', genre: 'Électro-pop' },
        { name: 'Kaïto', genre: 'Hyperpop' },
        { name: 'Lune Bleue', genre: 'Indie' },
        { name: 'Mira V.', genre: 'R&B alternatif' },
      ],
    },
    contracts: [
      {
        id: 'c1',
        title: "Contrat d'enregistrement — Album « Aurora »",
        party: 'Halo Records',
        type: 'Enregistrement',
        status: 'Actif',
        startDate: '2025-02-01',
        endDate: '2028-02-01',
        value: 45000,
        royaltyRate: 22,
        notes: '3 albums, avance récupérable. Option label pour 2 albums supplémentaires.',
      },
      {
        id: 'c2',
        title: "Contrat d'édition musicale",
        party: 'Sony Music Publishing',
        type: 'Édition',
        status: 'Actif',
        startDate: '2025-03-15',
        endDate: '2030-03-15',
        value: 30000,
        royaltyRate: 50,
        notes: 'Édition du catalogue 2025-2030. Partage 50/50 sur droits mécaniques.',
      },
      {
        id: 'c3',
        title: 'Mandat de booking — Tournée 2026',
        party: 'Live Nation France',
        type: 'Booking',
        status: 'En attente',
        startDate: '2026-09-01',
        endDate: '2027-06-30',
        value: 0,
        royaltyRate: 85,
        notes: 'Commission agence 15%. En attente des dates de salles.',
      },
      {
        id: 'c4',
        title: 'Licence sync — Spot TV « Été Vibrant »',
        party: 'Publicis Conseil',
        type: 'Licence',
        status: 'En attente',
        startDate: '2026-08-01',
        endDate: '2027-08-01',
        value: 12000,
        royaltyRate: 100,
        notes: 'Utilisation du titre « Néon » — diffusion France, 12 mois.',
      },
    ],
    concerts: [
      {
        id: 'g1',
        venue: 'La Cigale',
        city: 'Paris',
        country: 'France',
        date: '2026-08-14',
        time: '20:30',
        status: 'Confirmé',
        capacity: 1389,
        ticketsSold: 1120,
        fee: 8500,
        promoter: 'Live Nation',
        notes: 'Release party de l’album. Balances 16h.',
      },
      {
        id: 'g2',
        venue: 'Rockhal',
        city: 'Esch-sur-Alzette',
        country: 'Luxembourg',
        date: '2026-09-05',
        time: '21:00',
        status: 'Confirmé',
        capacity: 1200,
        ticketsSold: 640,
        fee: 6000,
        promoter: 'den Atelier',
        notes: '',
      },
      {
        id: 'g3',
        venue: 'Le Transbordeur',
        city: 'Lyon',
        country: 'France',
        date: '2026-09-19',
        time: '20:00',
        status: 'Option',
        capacity: 1800,
        ticketsSold: 0,
        fee: 7000,
        promoter: 'Totaal Rez',
        notes: 'Option jusqu’au 15/08.',
      },
      {
        id: 'g4',
        venue: 'AB Club',
        city: 'Bruxelles',
        country: 'Belgique',
        date: '2026-10-03',
        time: '20:30',
        status: 'Annoncé',
        capacity: 300,
        ticketsSold: 90,
        fee: 3500,
        promoter: 'Ancienne Belgique',
        notes: '',
      },
      {
        id: 'g5',
        venue: 'Festival Les Nuits Sonores',
        city: 'Lyon',
        country: 'France',
        date: '2026-05-28',
        time: '22:15',
        status: 'Terminé',
        capacity: 5000,
        ticketsSold: 5000,
        fee: 15000,
        promoter: 'Arty Farty',
        notes: 'Set de 60 min. Excellent retour presse.',
      },
    ],
    releases: [
      {
        id: 'r1',
        title: 'Aurora',
        type: 'Album',
        date: '2026-08-14',
        status: 'Master prêt',
        cover: '#8b5cf6',
        streams: 0,
        isrc: 'FR-Z03-26-00001',
        featuring: '',
        notes: '11 titres. Pochette validée. Promo dès le 20/07.',
      },
      {
        id: 'r2',
        title: 'Néon',
        type: 'Single',
        date: '2026-06-06',
        status: 'Publié',
        cover: '#ec4899',
        streams: 1240000,
        isrc: 'FR-Z03-26-00002',
        featuring: '',
        notes: 'Premier extrait de l’album. Playlist « New Music Friday ».',
      },
      {
        id: 'r3',
        title: 'Gravité',
        type: 'Single',
        date: '2026-07-18',
        status: 'Publié',
        cover: '#3b82f6',
        streams: 480000,
        isrc: 'FR-Z03-26-00003',
        featuring: 'Kaïto',
        notes: 'Second extrait, feat. Kaïto.',
      },
      {
        id: 'r4',
        title: 'Horizon (Remix)',
        type: 'Remix',
        date: '2026-09-12',
        status: 'Planifié',
        cover: '#10b981',
        streams: 0,
        isrc: '',
        featuring: '',
        notes: 'Remix club, en attente du master.',
      },
    ],
    royalties: [
      { id: 'y1', platform: 'Spotify', period: 'Juin 2026', streams: 820000, amount: 2870, color: '#1db954' },
      { id: 'y2', platform: 'Apple Music', period: 'Juin 2026', streams: 240000, amount: 1680, color: '#000000' },
      { id: 'y3', platform: 'Deezer', period: 'Juin 2026', streams: 130000, amount: 690, color: '#8b5cf6' },
      { id: 'y4', platform: 'YouTube Music', period: 'Juin 2026', streams: 310000, amount: 540, color: '#ff0000' },
      { id: 'y5', platform: 'Amazon Music', period: 'Juin 2026', streams: 70000, amount: 420, color: '#25d1da' },
      { id: 'y6', platform: 'Spotify', period: 'Mai 2026', streams: 610000, amount: 2130, color: '#1db954' },
      { id: 'y7', platform: 'Apple Music', period: 'Mai 2026', streams: 190000, amount: 1330, color: '#000000' },
      { id: 'y8', platform: 'Deezer', period: 'Mai 2026', streams: 95000, amount: 500, color: '#8b5cf6' },
      { id: 'y9', platform: 'YouTube Music', period: 'Mai 2026', streams: 250000, amount: 430, color: '#ff0000' },
    ],
    studio: [
      {
        id: 's1',
        title: 'Enregistrement voix — « Horizon »',
        studio: 'Studio Ferber',
        date: '2026-08-04',
        startTime: '10:00',
        endTime: '16:00',
        type: 'Enregistrement',
        cost: 650,
        engineer: 'Thomas R.',
        notes: 'Prévoir les topline finales.',
      },
      {
        id: 's2',
        title: 'Session mix — 3 titres',
        studio: 'La Frette Studios',
        date: '2026-08-08',
        startTime: '14:00',
        endTime: '20:00',
        type: 'Mix',
        cost: 900,
        engineer: 'Manon L.',
        notes: '',
      },
      {
        id: 's3',
        title: 'Répétition tournée',
        studio: 'HF Studios',
        date: '2026-08-11',
        startTime: '13:00',
        endTime: '18:00',
        type: 'Répétition',
        cost: 300,
        engineer: '—',
        notes: 'Filage complet du set + technique.',
      },
      {
        id: 's4',
        title: 'Mastering album « Aurora »',
        studio: 'Translab',
        date: '2026-07-31',
        startTime: '11:00',
        endTime: '15:00',
        type: 'Mastering',
        cost: 1200,
        engineer: 'Chab',
        notes: 'Master final avant pressage.',
      },
      {
        id: 's5',
        title: 'Session écriture',
        studio: 'Home Studio',
        date: '2026-08-20',
        startTime: '15:00',
        endTime: '19:00',
        type: 'Écriture',
        cost: 0,
        engineer: '—',
        notes: 'Nouveaux morceaux pour EP 2027.',
      },
    ],
    contacts: [
      {
        id: 'k1',
        name: 'Sophie Delatour',
        role: 'Directrice de label',
        company: 'Halo Records',
        category: 'Label',
        email: 'sophie@halorecords.fr',
        phone: '+33 6 12 34 56 78',
        favorite: true,
        notes: 'Interlocutrice principale. Point hebdo le lundi.',
      },
      {
        id: 'k2',
        name: 'Marc Vasseur',
        role: 'Agent / Booker',
        company: 'Live Nation France',
        category: 'Booking',
        email: 'm.vasseur@livenation.fr',
        phone: '+33 6 98 76 54 32',
        favorite: true,
        notes: 'Gère la tournée 2026.',
      },
      {
        id: 'k3',
        name: 'Julie Nkomo',
        role: 'Attachée de presse',
        company: 'Pressing Agency',
        category: 'Média',
        email: 'julie@pressing.agency',
        phone: '+33 7 11 22 33 44',
        favorite: false,
        notes: 'Promo album « Aurora ».',
      },
      {
        id: 'k4',
        name: 'Thomas Renard',
        role: 'Ingénieur du son',
        company: 'Studio Ferber',
        category: 'Studio',
        email: 'thomas@studioferber.com',
        phone: '+33 6 55 44 33 22',
        favorite: false,
        notes: '',
      },
      {
        id: 'k5',
        name: 'Me Claire Aubert',
        role: 'Avocate spécialisée musique',
        company: 'Aubert & Associés',
        category: 'Juridique',
        email: 'c.aubert@aubert-legal.fr',
        phone: '+33 1 42 00 00 00',
        favorite: false,
        notes: 'Relecture des contrats.',
      },
      {
        id: 'k6',
        name: 'David Klein',
        role: 'Manager',
        company: 'DK Management',
        category: 'Management',
        email: 'david@dkmanagement.com',
        phone: '+33 6 77 88 99 00',
        favorite: true,
        notes: 'Coordination générale de carrière.',
      },
    ],
    /*  Les dates sont relatives au jour d'ouverture, comme le reste de la
     *  démonstration : une échéance figée finirait par être toujours dépassée,
     *  et la liste ne montrerait plus qu'un mur de retards. */
    tasks: [
      {
        id: 't1',
        title: 'Relancer Halo Records sur l’avenant',
        done: false,
        due: inDays(2),
        priority: 'Haute',
        category: 'Contrat',
        notes: 'Point hebdo du lundi avec Sophie.',
        doneAt: '',
      },
      {
        id: 't2',
        title: 'Envoyer le dossier de presse aux radios',
        done: false,
        due: inDays(5),
        priority: 'Haute',
        category: 'Promotion',
        notes: '',
        doneAt: '',
      },
      {
        id: 't3',
        title: 'Valider le mastering de « Gravité »',
        done: false,
        due: inDays(9),
        priority: 'Normale',
        category: 'Studio',
        notes: '',
        doneAt: '',
      },
      {
        id: 't4',
        title: 'Réserver les billets de train pour Bruxelles',
        done: false,
        due: inDays(21),
        priority: 'Normale',
        category: 'Concert',
        notes: 'Concert de l’AB Club.',
        doneAt: '',
      },
      {
        id: 't5',
        title: 'Déclarer les cachets du trimestre',
        done: false,
        due: inDays(30),
        priority: 'Basse',
        category: 'Administratif',
        notes: '',
        doneAt: '',
      },
      {
        id: 't6',
        title: 'Déposer les titres à la SACEM',
        done: true,
        due: inDays(-6),
        priority: 'Haute',
        category: 'Administratif',
        notes: '',
        doneAt: inDays(-4),
      },
      {
        id: 't7',
        title: 'Commander les visuels du single',
        done: true,
        due: inDays(-12),
        priority: 'Normale',
        category: 'Sortie',
        notes: '',
        doneAt: inDays(-10),
      },
    ],
    accounts: [
      {
        id: 'a1', name: 'SNEP', handle: '@snep', role: 'Syndicat', verified: true, color: '#1d4ed8',
        company: 'Syndicat National de l’Édition Phonographique', location: 'Paris',
        bio: 'Représente les producteurs de musique en France. Publie les certifications et les chiffres du marché.',
        specialties: ['Certifications', 'Études de marché', 'Représentation'], connections: 4820,
      },
      {
        id: 'a2', name: 'Mehdi Larbi', handle: '@mehdi.rap', role: 'Journaliste', verified: true, color: '#db2777',
        company: 'Indépendant', location: 'Paris',
        bio: 'Journaliste musical depuis douze ans. Interviews longues, rap et musiques urbaines. Ouvert aux propositions d’artistes émergents.',
        specialties: ['Interview', 'Rap', 'Podcast', 'Critique'], connections: 1960,
      },
      {
        id: 'a3', name: 'Halo Records', handle: '@halorecords', role: 'Label', verified: true, color: '#8b5cf6',
        company: 'Halo Records', location: 'Paris',
        bio: 'Label indépendant fondé en 2019. Électro-pop et nouvelles scènes. Quatre artistes au roster.',
        specialties: ['Signature', 'Production', 'Développement d’artiste'], connections: 870,
      },
      {
        id: 'a4', name: 'SACEM', handle: '@sacem', role: 'Société de droits', verified: true, color: '#0d9488',
        company: 'SACEM', location: 'Neuilly-sur-Seine',
        bio: 'Gestion collective des droits d’auteur. Aides à la création, à la production et à la diffusion.',
        specialties: ['Droits d’auteur', 'Aides', 'Dépôt d’œuvres'], connections: 12400,
      },
      {
        id: 'a5', name: 'Believe', handle: '@believe', role: 'Distributeur', verified: true, color: '#0ea5e9',
        company: 'Believe', location: 'Paris',
        bio: 'Distribution numérique et services aux artistes indépendants. Relevés mensuels et marketing digital.',
        specialties: ['Distribution', 'Royalties', 'Marketing digital'], connections: 9100,
      },
      {
        id: 'a6', name: 'Kaïto', handle: '@kaito', role: 'Artiste', verified: false, color: '#f59e0b',
        company: 'Halo Records', location: 'Lyon',
        bio: 'Producteur et interprète hyperpop. Deux EP sortis, ouvert aux featurings et aux collaborations studio.',
        specialties: ['Hyperpop', 'Production', 'Topline'], connections: 640,
      },
      {
        id: 'a7', name: 'La Cigale', handle: '@lacigale', role: 'Salle', verified: true, color: '#dc2626',
        company: 'La Cigale', location: 'Paris 18e',
        bio: 'Salle de concert de 1 389 places. Programmation éclectique, accueil des tournées françaises et internationales.',
        specialties: ['Programmation', 'Accueil tournée', 'Billetterie'], connections: 2310,
      },
      {
        id: 'a8', name: 'Scène Ouverte', handle: '@sceneouverte', role: 'Média', verified: false, color: '#7c3aed',
        company: 'Scène Ouverte', location: 'Nantes',
        bio: 'Média indépendant consacré aux musiques actuelles. Enquêtes sur l’économie du secteur et portraits d’artistes.',
        specialties: ['Enquête', 'Portrait', 'Économie de la musique'], connections: 1480,
      },
      {
        id: 'a9', name: 'Lune Bleue', handle: '@lunebleue', role: 'Artiste', verified: false, color: '#2563eb',
        company: 'Halo Records', location: 'Bordeaux',
        bio: 'Projet indie-folk en trio. Tournée régionale à l’automne, cherche régulièrement des premières parties.',
        specialties: ['Indie', 'Folk', 'Live'], connections: 520,
      },
      {
        id: 'a10', name: 'Thomas Renard', handle: '@thomas.son', role: 'Ingénieur du son', verified: false, color: '#059669',
        company: 'Studio Ferber', location: 'Paris',
        bio: 'Prise de son, mixage et mastering. Quinze ans de studio, spécialisé voix et musiques électroniques.',
        specialties: ['Mixage', 'Mastering', 'Prise de son', 'Voix'], connections: 1120,
      },
      {
        id: 'a11', name: 'Marc Vasseur', handle: '@marc.booking', role: 'Booker', verified: true, color: '#ea580c',
        company: 'Live Nation France', location: 'Paris',
        bio: 'Agent et programmateur de tournées. Accompagne une dizaine de projets français en développement.',
        specialties: ['Booking', 'Tournée', 'Négociation'], connections: 3450,
      },
      {
        id: 'a12', name: 'Julie Nkomo', handle: '@julie.presse', role: 'Attachée de presse', verified: false, color: '#c026d3',
        company: 'Pressing Agency', location: 'Paris',
        bio: 'Relations presse et médias pour les musiques actuelles. Campagnes de sortie d’album et de single.',
        specialties: ['Relations presse', 'Promotion', 'Radio'], connections: 1730,
      },
    ],
    posts: [
      {
        id: 'p1',
        accountId: 'a1',
        category: 'Certification',
        content:
          "Nouvelle certification : le single « Néon » de NOVA est certifié SINGLE D'OR (15 millions d'équivalents streams). Félicitations à l'artiste et à Halo Records.",
        date: hoursAgo(3),
        likes: 1284,
        comments: 96,
        liked: false,
        saved: false,
        tags: ['certification', 'or', 'electro-pop'],
      },
      {
        id: 'p2',
        accountId: 'a2',
        category: 'Interview',
        content:
          "Demain 18h, je publie une interview longue avec NOVA : la fabrication de l'album « Aurora », le rapport au live et la question des royalties dans l'électro indépendante. Un échange sans filtre.",
        date: hoursAgo(6),
        likes: 432,
        comments: 51,
        liked: false,
        saved: true,
        tags: ['interview', 'aurora'],
      },
      {
        id: 'p3',
        accountId: 'a4',
        category: 'Industrie',
        content:
          "Rappel : les demandes d'aide à la création pour le programme automne se clôturent le 30 septembre. Les artistes autoproduits sont éligibles dès un titre déposé.",
        date: hoursAgo(11),
        likes: 297,
        comments: 34,
        liked: false,
        saved: false,
        tags: ['aide', 'financement'],
      },
      {
        id: 'p4',
        accountId: 'a3',
        category: 'Sortie',
        content:
          "« Aurora », premier album de NOVA, sort le 14 août. 11 titres, deux ans de travail. Précommandes ouvertes, vinyle en édition limitée à 500 exemplaires.",
        date: hoursAgo(20),
        likes: 856,
        comments: 73,
        liked: true,
        saved: false,
        tags: ['album', 'aurora', 'vinyle'],
      },
      {
        id: 'p5',
        accountId: 'a5',
        category: 'Industrie',
        content:
          'Les relevés de juillet sont disponibles dans votre espace. Rappel utile : le versement intervient environ deux mois après le mois de diffusion.',
        date: hoursAgo(26),
        likes: 165,
        comments: 22,
        liked: false,
        saved: false,
        tags: ['royalties', 'relevé'],
      },
      {
        id: 'p6',
        accountId: 'a7',
        category: 'Concert',
        content:
          "Complet ! La release party de NOVA le 14 août affiche guichet fermé. Une seconde date est à l'étude pour l'automne.",
        date: hoursAgo(32),
        likes: 640,
        comments: 88,
        liked: false,
        saved: false,
        tags: ['concert', 'paris', 'complet'],
      },
      {
        id: 'p7',
        accountId: 'a6',
        category: 'Sortie',
        content:
          "Mon featuring avec NOVA sur « Gravité » passe les 500 000 écoutes. Merci à tous. On remet ça bientôt en studio.",
        date: hoursAgo(44),
        likes: 512,
        comments: 61,
        liked: false,
        saved: false,
        tags: ['featuring', 'hyperpop'],
      },
      {
        id: 'p8',
        accountId: 'a8',
        category: 'Industrie',
        content:
          "Enquête : combien gagne réellement un artiste indépendant sur 1 million de streams ? Nous avons comparé cinq plateformes et interrogé sept artistes. À lire cette semaine.",
        date: hoursAgo(52),
        likes: 923,
        comments: 147,
        liked: false,
        saved: true,
        tags: ['enquête', 'streaming', 'revenus'],
      },
      {
        id: 'p9',
        accountId: 'a1',
        category: 'Certification',
        content:
          'Bilan du premier semestre : le streaming représente désormais 78 % des revenus de la musique enregistrée en France. Le vinyle poursuit sa progression.',
        date: hoursAgo(70),
        likes: 388,
        comments: 42,
        liked: false,
        saved: false,
        tags: ['marché', 'streaming', 'vinyle'],
      },
      {
        id: 'p10',
        accountId: 'a9',
        category: 'Concert',
        content:
          "Je cherche une première partie pour ma tournée de novembre, cinq dates en région. Électro, indie ou pop alternative. Écrivez-moi.",
        date: hoursAgo(78),
        likes: 214,
        comments: 96,
        liked: false,
        saved: false,
        tags: ['tournée', 'première partie'],
      },
    ],
    opportunities: [
      {
        id: 'o1', accountId: 'a9', title: 'Première partie recherchée — tournée régionale',
        role: 'Artiste', kind: 'Rémunéré', location: '5 dates en région',
        description: 'Nous cherchons une première partie pour cinq dates en novembre. Électro, indie ou pop alternative. Set de 30 minutes, cachet et transport pris en charge.',
        date: hoursAgo(9), deadline: '2026-09-15', saved: false,
      },
      {
        id: 'o2', accountId: 'a3', title: 'Recherche bassiste pour session studio',
        role: 'Musicien', kind: 'Rémunéré', location: 'Paris',
        description: 'Deux jours de studio début septembre pour un projet électro-pop. Lecture souhaitée, matériel fourni. Rémunération au cachet.',
        date: hoursAgo(22), deadline: '2026-08-28', saved: false,
      },
      {
        id: 'o3', accountId: 'a10', title: 'Créneaux de mixage disponibles',
        role: 'Ingénieur du son', kind: 'Rémunéré', location: 'Studio Ferber, Paris',
        description: 'Trois créneaux libres en septembre pour du mixage ou du mastering. Tarif dégressif à partir de trois titres.',
        date: hoursAgo(30), deadline: '', saved: true,
      },
      {
        id: 'o4', accountId: 'a2', title: 'Appel à artistes émergents pour interviews',
        role: 'Artiste', kind: 'Bénévole', location: 'À distance ou Paris',
        description: 'Je consacre une série d’interviews aux artistes autoproduits. Envoyez deux titres et quelques lignes sur votre parcours.',
        date: hoursAgo(40), deadline: '2026-10-01', saved: false,
      },
      {
        id: 'o5', accountId: 'a7', title: 'Programmation soirée découverte',
        role: 'Artiste', kind: 'Rémunéré', location: 'Paris 18e',
        description: 'Deux places à pourvoir sur notre soirée découverte de novembre. Projets franciliens en développement, un premier EP minimum.',
        date: hoursAgo(54), deadline: '2026-09-30', saved: false,
      },
      {
        id: 'o6', accountId: 'a6', title: 'Échange de featurings',
        role: 'Artiste', kind: 'Collaboration', location: 'À distance',
        description: 'Je propose un échange : un couplet chez moi contre un couplet chez vous. Hyperpop, électro ou pop alternative.',
        date: hoursAgo(66), deadline: '', saved: false,
      },
    ],
    following: ['a1', 'a2', 'a3', 'a4'],
    // Une journée en arrière : les publications récentes apparaissent comme
    // non lues au premier lancement.
    networkLastSeen: hoursAgo(24),
  }
}

/**
 * Date ISO dans `j` jours. Négatif pour une date passée — les tâches déjà
 * faites en ont besoin, sans quoi elles paraîtraient cochées d'avance.
 */
function inDays(j: number): string {
  return new Date(Date.now() + j * 86_400_000).toISOString().slice(0, 10)
}

/**
 * Point de départ d'un nouveau compte : un seul exemple par rubrique visible.
 *
 * Ni le catalogue de démonstration complet — les concerts d'une autre artiste
 * n'ont rien à faire dans un compte personnel — ni des écrans entièrement
 * vides, où l'on ne devine pas ce qu'une fiche est censée contenir. Chaque
 * exemple est préfixé « Exemple » pour être reconnu et supprimé sans hésiter.
 *
 * Les rubriques réservées à l'offre Pro n'en reçoivent pas : l'exemple y serait
 * invisible, et son seul effet serait de gonfler un compteur.
 *
 * Le Réseau garde son contenu : c'est le seul onglet dont les données ne sont
 * pas censées venir de l'artiste.
 */
export function starterData(): AppData {
  const base = seedData()
  return {
    ...base,
    onboarded: false,
    artist: {
      stageName: '',
      realName: '',
      genre: '',
      city: '',
      photo: '',
      bio: '',
      email: '',
      phone: '',
      instagram: '',
      spotify: '',
      website: '',
    },
    label: {
      name: '',
      tagline: '',
      founded: '',
      location: '',
      email: '',
      website: '',
      distribution: '',
      publishing: '',
      roster: [],
    },
    /*  Aucun exemple de contrat, contrairement aux autres rubriques : l'onglet
     *  Contrats est réservé à l'offre Pro, l'exemple y resterait donc invisible
     *  pour un compte gratuit. Il ne s'y montrait que par son compteur — un
     *  « 1 contrat en attente » sur le tableau de bord et dans le menu, qu'il
     *  était impossible de ramener à zéro sans s'abonner. */
    contracts: [],
    concerts: [
      {
        id: 'ex-concert',
        venue: 'Exemple — Nom de la salle',
        city: 'Ville',
        country: 'France',
        date: inDays(30),
        time: '20:30',
        status: 'Option',
        capacity: 200,
        ticketsSold: 0,
        fee: 0,
        promoter: '',
        notes: 'Exemple à modifier ou supprimer.',
      },
    ],
    releases: [
      {
        id: 'ex-sortie',
        title: 'Exemple — Mon premier single',
        type: 'Single',
        date: inDays(60),
        status: 'Planifié',
        cover: '#8b5cf6',
        streams: 0,
        isrc: '',
        featuring: '',
        notes: 'Exemple à modifier ou supprimer.',
      },
    ],
    royalties: [],
    studio: [
      {
        id: 'ex-agenda',
        title: 'Exemple — Répétition',
        studio: 'Lieu',
        date: inDays(7),
        startTime: '14:00',
        endTime: '18:00',
        type: 'Répétition',
        cost: 0,
        engineer: '',
        notes: 'Exemple à modifier ou supprimer.',
      },
    ],
    contacts: [
      {
        id: 'ex-contact',
        name: 'Exemple — Programmateur',
        role: 'Programmation',
        company: 'Structure',
        category: 'Booking',
        email: '',
        phone: '',
        favorite: false,
        notes: 'Exemple à modifier ou supprimer.',
      },
    ],
    tasks: [
      {
        id: 'ex-task',
        title: 'Exemple — préparer le dossier de presse',
        done: false,
        due: inDays(7),
        priority: 'Normale',
        category: 'Promotion',
        notes: 'Exemple à modifier ou supprimer.',
        doneAt: '',
      },
    ],
  }
}
